"""Task data + behavior.

`TaskData` is the wire half: a frozen pydantic model carrying the data which
initializes a task instance. Rides on `trace.task.data` in `traces.jsonl`.

`Task` is the behavior half: runtime prep (`setup`/`finalize`), tool servers
(`toolsets`), and scoring (`@reward`/`@metric`) methods.
"""

from __future__ import annotations

import copy
import hashlib
import inspect
import json
import logging
from collections.abc import Callable, Mapping
from typing import TYPE_CHECKING, Any, ClassVar, Generic, Self

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeVar

from verifiers.v1.configs.task import TaskConfig
from verifiers.v1.errors import TaskError, boundary
from verifiers.v1.state import StateT
from verifiers.v1.types import Messages, content_text
from verifiers.v1.utils.artifacts import Artifact
from verifiers.v1.utils.decorators import (
    discover_decorated,
    invoke_all,
    seed,
    unseed,
)
from verifiers.v1.utils.generic import concrete_type

if TYPE_CHECKING:
    from verifiers.v1.judge import Judge
    from verifiers.v1.mcp import Toolset
    from verifiers.v1.runtimes import Runtime
    from verifiers.v1.trace import Trace

logger = logging.getLogger(__name__)


def task_key(data: Mapping) -> str:
    """Content identity for task wire data, independent of field order."""
    return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()


class TaskResources(BaseModel):
    """Optional resource limits for the task."""

    model_config = ConfigDict(frozen=True)

    cpu: float | None = None
    """CPU cores."""
    memory: float | None = None
    """Memory in GB."""
    gpu: str | None = None
    """GPU spec, e.g. "A100" or "A100:2" (type[:count])."""
    disk: float | None = None
    """Disk in GB (enforced by prime; advisory on docker/modal)."""


class TaskTimeout(BaseModel):
    """Optional per-task timeout overrides, in seconds."""

    model_config = ConfigDict(frozen=True)

    setup: float | None = None
    """Timeout (in seconds) for the task's setup hook."""
    agent: float | None = None
    """Timeout (in seconds) for the agent's solve attempt."""
    finalize: float | None = None
    """Timeout (in seconds) for the task's finalize hook."""
    scoring: float | None = None
    """Timeout (in seconds) for the task's scoring."""


class TaskData(BaseModel):
    model_config = ConfigDict(frozen=True)

    idx: int | None = None
    """Taskset-autogenerated index."""
    name: str | None = None
    """Optional human-readable task name."""
    description: str | None = None
    """Optional human-readable task description."""

    prompt: str | Messages | None = None
    """Initial user prompt; unset if the user opens the conversation."""
    system_prompt: str | None = None
    """Optional system prompt to prepend to the user prompt."""

    image: str | None = None
    """Optional Docker image to use for the task. Only relevant for tasks that run in a container."""
    workdir: str | None = None
    """Optional working directory to use for the task. Only relevant for tasks that run in a container."""

    network_allow: list[str] = Field(default_factory=lambda: ["*"])
    """Execution-time destinations requested by this task. `*` leaves the runtime
    allowlist unchanged; a concrete list replaces a wildcard or retains entries also
    present in an existing allowlist. Prime runtimes accept host-level entries and
    require `vm=true`."""
    network_block: list[str] = Field(default_factory=list)
    """Execution-time destinations denied by this task and combined with runtime
    blocks. Non-empty concrete allowlists cannot be combined with blocklists. Docker
    framework routes take precedence; ordinary Prime deny rules pass through unchanged."""

    artifacts: list[Artifact] = Field(default_factory=list)
    """Paths collected from one runtime and restored at the same locations in another,
    on top of the implicitly collected `/logs/artifacts/` convention dir. Declare
    runtime outputs that must cross that boundary. A declared path that is missing at
    collection time fails the rollout."""

    timeout: TaskTimeout = TaskTimeout()
    resources: TaskResources = TaskResources()

    @property
    def prompt_text(self) -> str:
        if isinstance(self.prompt, str):
            return self.prompt
        texts = [content_text(message.content) for message in self.prompt or []]
        return "\n\n".join(text for text in texts if text)


class WireTaskData(TaskData):
    """Wire form that preserves task-specific fields without importing the task class."""

    model_config = ConfigDict(extra="allow")


DataT = TypeVar("DataT", bound=TaskData)
ConfigT = TypeVar("ConfigT", bound=TaskConfig, default=TaskConfig)


class Task(Generic[DataT, StateT, ConfigT]):
    NEEDS_CONTAINER: ClassVar[bool] = False
    """Whether the task needs a containerized environment (isolated filesystem, ...)."""

    def __init__(self, data: DataT, config: ConfigT | None = None) -> None:
        self.data = data
        self.config = config if config is not None else self.config_type()()

    @property
    def hash(self) -> str:
        """Content hash of the task's wire data, recorded on the trace as
        ``task.hash``."""
        return task_key(self.data.model_dump(mode="json", exclude_none=True))

    @property
    def key(self) -> str:
        """Stable task identity, recorded on the trace as ``task.key``.

        The content hash is the default. Override this when the task data contains
        run-local fields such as an autogenerated ``idx`` and the underlying dataset
        provides a durable identifier. Keys must be unique within a taskset.
        """
        return self.hash

    def with_system_prompt(self, system_prompt: str) -> Self:
        clone = copy.copy(self)
        clone.data = self.data.model_copy(update={"system_prompt": system_prompt})
        return clone

    def runtime_env(self) -> dict[str, str]:
        """Live-only process environment; unlike TaskData, it is not traced."""
        return {}

    async def setup(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def finalize(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def stage_verifier(self, trace: Trace, runtime: Runtime) -> None:
        """Prepare trusted verifier-only inputs after artifacts are restored."""
        return

    async def validate(self, runtime: Runtime) -> bool | None:
        """Check the ground truth, or return None when no model-free check exists."""
        return None

    def defer_scoring(self) -> Self:
        """An independent copy whose task signals are deferred.

        Lifecycle hooks still run normally: in particular, ``finalize`` can prepare
        state before declared artifacts are collected and the solver runtime is
        destroyed. Only task metrics, rewards, and judges are skipped; harness
        metrics remain attached to the solver trace.
        """
        clone = copy.deepcopy(self)
        clone.scoring_deferred = True
        return clone

    scoring_deferred: bool = False

    async def score(
        self,
        trace: Trace,
        runtime: Runtime | None = None,
    ) -> None:
        if self.scoring_deferred:
            return

        def requires_runtime(fn) -> bool:
            param = inspect.signature(fn).parameters.get("runtime")
            # A defaulted runtime parameter can still be called offline with None.
            return param is not None and param.default is inspect.Parameter.empty

        judges = self.plugged_judges()
        available = {"task": self.data, "trace": trace}
        if runtime is not None:
            available["runtime"] = runtime

        async with boundary(TaskError, f"task {type(self).__name__} scoring"):
            metrics = self.hooks("metric")
            rewards = self.hooks("reward")
            if runtime is None:
                skipped = [
                    fn.__name__ for fn in (*metrics, *rewards) if requires_runtime(fn)
                ] + [
                    judge.reward_name
                    for judge in judges
                    if requires_runtime(judge.score)
                ]
                if skipped:
                    logger.info(
                        "score: no runtime — skipped runtime-dependent signals: %s",
                        skipped,
                    )
                metrics = [fn for fn in metrics if not requires_runtime(fn)]
                rewards = [fn for fn in rewards if not requires_runtime(fn)]
                judges = [
                    judge for judge in judges if not requires_runtime(judge.score)
                ]

            seed(trace.metrics, (fn.__name__ for fn in metrics))
            seed(trace.rewards, (fn.__name__ for fn in rewards))
            seed(trace.rewards, (judge.reward_name for judge in judges))

            metric_results = await invoke_all(metrics, available)
            for fn, result in zip(metrics, metric_results):
                if isinstance(result, Mapping):
                    unseed(trace.metrics, fn.__name__)
                    trace.record_metrics(result)
                else:
                    trace.record_metric(fn.__name__, result)
            reward_results = await invoke_all(rewards, available)
            for fn, result in zip(rewards, reward_results):
                weight = getattr(fn, "_vf_weight", 1.0)
                if isinstance(result, Mapping):
                    unseed(trace.rewards, fn.__name__)
                    items = result.items()
                else:
                    items = [(fn.__name__, result)]
                for key, value in items:
                    trace.record_reward(key, value, weight)
            judge_results = await invoke_all(
                [judge.score for judge in judges], available
            )
            for judge, result in zip(judges, judge_results):
                if isinstance(result, Mapping):
                    unseed(trace.rewards, judge.reward_name)
                    items = result.items()
                else:
                    items = [(judge.reward_name, result)]
                for key, value in items:
                    trace.record_reward(key, value, judge.config.weight)

    @classmethod
    def data_type(cls) -> type[TaskData]:
        return concrete_type(cls, TaskData) or TaskData

    @classmethod
    def config_type(cls) -> type[TaskConfig]:
        return concrete_type(cls, TaskConfig) or TaskConfig

    def plugged_judges(self) -> list[Judge]:
        from verifiers.v1.utils.loaders import load_judge

        return [load_judge(config) for config in self.config.judges]

    def hooks(self, attr: str) -> list[Callable[..., Any]]:
        """The task's `@vf.<attr>` methods merged with the config-plugged functions —
        a plugged function replaces a decorated method with the same name (a `fn`-less
        entry only overrides its metadata) — sorted by descending priority then name."""
        from verifiers.v1.utils.loaders import load_plugged_fn

        plugged = {
            "stop": self.config.stops,
            "metric": self.config.metrics,
            "reward": self.config.rewards,
        }[attr]
        merged = {fn.__name__: fn for fn in discover_decorated(self, attr)}
        merged |= {
            name: load_plugged_fn(name, spec, attr, decorated=merged.get(name))
            for name, spec in plugged.items()
        }
        fns = list(merged.values())
        fns.sort(key=lambda fn: (-getattr(fn, f"{attr}_priority", 0), fn.__name__))
        return fns

    @classmethod
    def toolsets(cls, config: ConfigT) -> list[Toolset]:
        """Tool servers launched per rollout, each constructed with its config off
        `config` — override and wire explicitly:

            @classmethod
            def toolsets(cls, config: MyTaskConfig) -> list[vf.Toolset]:
                return [SearchToolset(config.tools)]

        A classmethod so consumers can size placement (tunnels) off the class
        before any task instance exists."""
        return []


TaskT = TypeVar("TaskT", bound=Task)
